services:
  redpanda_destination:
    command:
      - redpanda
      - start
      - --node-id
      - '0'
      - --kafka-addr
      - 'default://0.0.0.0:29092'
      - --advertise-kafka-addr
      - 'default://127.0.0.1:29092'
      - --smp
      - '1'
      - --memory
      - '512M'
      - --reserve-memory
      - '0M'
      - --overprovisioned
      - --check=false
      - --default-log-level=info
      - --set redpanda.developer_mode=true
      - '--set redpanda.kafka_api_tls={"name":"default","enabled":true,"require_client_auth":true,"cert_file":"/etc/redpanda/certs/dst.crt","key_file":"/etc/redpanda/certs/dst.key","truststore_file":"/etc/redpanda/certs/ca.crt"}'
      - '--set redpanda.admin_api_tls={"enabled":true,"require_client_auth":true,"cert_file":"/etc/redpanda/certs/dst.crt","key_file":"/etc/redpanda/certs/dst.key","truststore_file":"/etc/redpanda/certs/ca.crt"}'
    image: 'docker.vectorized.io/vectorized/redpanda:v22.1.3'
    container_name: 'redpanda_destination'
    volumes:
      - ./certs:/etc/redpanda/certs
    ports:
      - "29092:29092"
      - "29644:9644"
