id:
create_topics: false
source:
  bootstrap_servers: 127.0.0.1:19092
  topics:
    - test
  default_partitions: 1
  default_replication: 1
destination:
  bootstrap_servers: 127.0.0.1:29092
  default_partitions: 1
  default_replication: 1
